export const months = [
  { value: 1, label: 'January' },
  { value: 2, label: 'February'},
  { value: 3, label: 'March' },
  { value: 4, label: 'April'},
  { value: 5, label: 'May' },
  { value: 6, label: 'June' },
  { value: 7, label: 'July' },
  { value: 8, label: 'August' },
  { value: 9, label: 'September' },
  { value: 10, label: 'October' },
  { value: 11, label: 'November' },
  { value: 12, label: 'December' }
];

// https://www.hrc.org/resources/lgbt-inclusive-intake-forms
export const genders = [
  { value: 'f', label: 'Female' },
  { value: 'm', label: 'Male' },
  { value: 'ftm', label: 'Female-to-male' },
  { value: 'mtf', label: 'Male-to-female' }
];

export const maritalStatuses = [
  { value: 'single', label: 'Single' },
  { value: 'married', label: 'Married' },
  { value: 'domestic-partnership', label: 'Domestic partnership' },
  { value: 'divorced', label: 'Divorced' },
  { value: 'widowed', label: 'Widowed' }
];

export const usStates = [
  { value: 'AK', label: 'AK' },
  { value: 'AL', label: 'AL' },
  { value: 'AR', label: 'AR' },
  { value: 'AZ', label: 'AZ' },
  { value: 'AS', label: 'AS' },
  { value: 'CA', label: 'CA' },
  { value: 'CO', label: 'CO' },
  { value: 'CT', label: 'CT' },
  { value: 'DC', label: 'DC' },
  { value: 'DE', label: 'DE' },
  { value: 'FL', label: 'FL' },
  { value: 'GA', label: 'GA' },
  { value: 'GU', label: 'GU' },
  { value: 'HI', label: 'HI' },
  { value: 'IA', label: 'IA' },
  { value: 'ID', label: 'ID' },
  { value: 'IL', label: 'IL' },
  { value: 'IN', label: 'IN' },
  { value: 'KS', label: 'KS' },
  { value: 'KY', label: 'KY' },
  { value: 'LA', label: 'LA' },
  { value: 'MA', label: 'MA' },
  { value: 'MD', label: 'MD' },
  { value: 'ME', label: 'ME' },
  { value: 'MI', label: 'MI' },
  { value: 'MN', label: 'MN' },
  { value: 'MO', label: 'MO' },
  { value: 'MP', label: 'MP' },
  { value: 'MS', label: 'MS' },
  { value: 'MT', label: 'MT' },
  { value: 'NC', label: 'NC' },
  { value: 'ND', label: 'ND' },
  { value: 'NE', label: 'NE' },
  { value: 'NH', label: 'NH' },
  { value: 'NJ', label: 'NJ' },
  { value: 'NM', label: 'NM' },
  { value: 'NV', label: 'NV' },
  { value: 'NY', label: 'NY' },
  { value: 'OH', label: 'OH' },
  { value: 'OK', label: 'OK' },
  { value: 'OR', label: 'OR' },
  { value: 'PA', label: 'PA' },
  { value: 'PR', label: 'PR' },
  { value: 'RI', label: 'RI' },
  { value: 'SC', label: 'SC' },
  { value: 'SD', label: 'SD' },
  { value: 'TN', label: 'TN' },
  { value: 'TX', label: 'TX' },
  { value: 'UM', label: 'UM' },
  { value: 'UT', label: 'UT' },
  { value: 'VA', label: 'VA' },
  { value: 'VI', label: 'VI' },
  { value: 'VT', label: 'VT' },
  { value: 'WA', label: 'WA' },
  { value: 'WI', label: 'WI' },
  { value: 'WV', label: 'WV' },
  { value: 'WY', label: 'WY' },
];

export const conditions = [
  'Cancer',
  'Heart disease',
  'Diabetes',
  'Stroke',
  'High blood pressure',
  'High cholesterol',
  'Liver disease',
  'Alcohol/drug abuse',
  'Anxiety/depression',
  'Tuberculosis',
  'Anesthesia complications',
  'Genetic disorder',
  'Hypertension',
  'Heart attack',
  'Chronic bronchitis',
  'Hepatitis',
  'Back pain',
  'Psychotic disorder',
  'Irritable bowel syndrome',
  'Seizures',
  'Substance abuse',
  'Kidney disease',
  'HIV',
  'Gastro esophageal reflux disease',
  'Thyroid disease',
  'Bipolar',
  'Eye disease',
  'Arthritis',
  'Asthma',
  'Dementia',
  'ADD/ADHD'
];

// http://www.mapharm.com/forms_meds.htm
export const commonMeds = [
  { value: 'Vicodin', label: 'Vicodin' },
  { value: 'Hydrocodone', label: 'Hydrocodone' },
  { value: 'Lortab', label: 'Lortab' },
  { value: 'Oxycontin', label: 'Oxycontin' },
  { value: 'Percocet', label: 'Percocet' },
  { value: 'Clarocet NRI', label: 'Clarocet NRI' },
  { value: 'Alprazolam', label: 'Alprazolam' },
  { value: 'Ambien', label: 'Ambien' },
  { value: 'Ativan', label: 'Ativan' },
  { value: 'Diazepam', label: 'Diazepam' },
  { value: 'Adipex', label: 'Adipex' },
  { value: 'Phentermine', label: 'Phentermine' },
  { value: 'Renova', label: 'Renova' },
  { value: 'Retin-A', label: 'Retin-A' },
  { value: 'Vaniqa', label: 'Vaniqa' },
  { value: 'Sustanon', label: 'Sustanon' },
  { value: 'Deca Durabolin', label: 'Deca Durabolin' },
  { value: 'Max Vitality', label: 'Max Vitality' },
  { value: 'Max Breasts', label: 'Max Breasts' },
  { value: 'Viagra', label: 'Viagra' },
  { value: 'Propecia', label: 'Propecia' },
  { value: 'Zyban', label: 'Zyban' },
  { value: 'Ortho Tri Cyclen', label: 'Ortho Tri Cyclen' },
  { value: 'B Vitamins', label: 'B Vitamins' },
  { value: 'Calcium', label: 'Calcium' },
  { value: 'Coenzyme Q10', label: 'Coenzyme Q10' },
  { value: 'Fish Oil', label: 'Fish Oil' },
  { value: 'Folic Acid', label: 'Folic Acid' },
  { value: 'Iron', label: 'Iron' },
  { value: 'Melatonin', label: 'Melatonin' },
  { value: 'Multivitamins', label: 'Multivitamins' }
];

export const habits = [
  { name: 'alcohol', question: 'Do you drink alcohol?' },
  { name: 'tobacco', question: 'Do you smoke any tobacco products?' },
  { name: 'drugs', question: 'Have you regularly used illicit drugs?' }
];

export const habitFreq = 'frequency n/a';

export const familyMembers = [
  { value: 'mother', label: 'Mother' },
  { value: 'father', label: 'Father' },
  { value: 'mgrandmother', label: 'Maternal grandmother' },
  { value: 'mgrandfather', label: 'Maternal grandfather' },
  { value: 'pgrandmother', label: 'Paternal grandmother' },
  { value: 'pgrandfather', label: 'Paternal grandfather' },
  { value: 'sibling', label: 'Sibling' }
];
